# Generated by Django 4.2.11 on 2024-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packets',
            name='data',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='description',
        ),
        migrations.AddField(
            model_name='packets',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
